feat: 🎸 move funds endpoint
PolymeshAssociation/polymesh-private-rest-api pull request #26
Opened 2024-08-02 13:38 UTC by sansan

### JIRA Link 

https://polymesh.atlassian.net/browse/DA-1234

### Changelog / Description 

- adds endpoint to move funds between Confidential accounts owned by the signing Identity

### Checklist - 

- [x] New Feature ?
- [x] Updated swagger annotation (if API structure is changed) ?
- [x] Unit Test (if possible) ?
- [x] Updated the Readme.md (if required) ?

2024-08-06 13:11 UTC, prashantasdeveloper requested changes

2024-08-06 13:11 UTC, prashantasdeveloper commented on src/confidential-accounts/confidential-accounts.service.ts
> +  public async moveFunds(params: MoveFundsDto): ServiceReturn<void> {
This method should actually generate proof using the proof server and then submit to SDK. Check other methods where proof is being generated for reference

2024-08-06 13:11 UTC, prashantasdeveloper commented on src/confidential-accounts/dto/move-funds.dto.ts
> +  @IsArray()
@Type decorator missing

2024-08-06 13:11 UTC, prashantasdeveloper commented on src/confidential-accounts/dto/proof.dto.ts
> +  readonly proof: string;
You need to take the amount so that proof is generated using the proof server API

2024-08-09 13:19 UTC, polymath-eric approved these changes

2024-08-13 09:43 UTC, prashantasdeveloper approved these changes

2024-08-13 10:11 UTC, merged